[package]
name = "emu-8080"
version = "0.1.0"
authors = ["Michael Winkworth <mwinkwo@btinternet.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0.2"
enum-map = "1.1.1"
sdl2 = { version = "0.34.5", features = ["mixer"] }
log = "0.4.14"
env_logger = "0.9.0"

[dev-dependencies]
mutagen = { git = "https://github.com/llogiq/mutagen" }
